---
name: untitled
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  quiver: ^3.1.0
  intl: ^0.17.0
  image_picker: ^0.8.5
  firebase_auth: ^3.3.14
  firebase_core: ^1.15.0
  flutter_bloc: ^8.0.1
  flutter_offline: ^2.1.0
  uuid: ^3.0.6
  firebase_storage: ^10.2.14
  bloc: ^8.0.3
  flutter_hooks: ^0.18.3
  equatable: ^2.0.3
  email_validator: ^2.0.1
  cloud_firestore: ^3.1.14
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
